export class GodownDeliveryModel{
    id:number;
    gatepassNo:number;
    gatepassdate:Date;
    paymentmode:string;
    deliveryparty:number;
    deliverypartydetails:string;
    contractparty:number;
    contractpartydetails:string;
    CNno:string;
    CNdate:Date;
    bookingbranch:number;
    consignor:string;
    item:string;
    packingType:number;
    godownname:number;
    virtualgodownname:number;
    deliveryarticle:number;
    deliveryweight:number;
    balancearticle:number;
    balanceweight:number;
    rollno:string;
    handedoverto:string;
    contractNo:number;
    vehicleNo:number;
    GUTKANo:string;
    remark:string;
}