//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankMaster()
        {
            this.VendorMasters = new HashSet<VendorMaster>();
            this.VendorMasters1 = new HashSet<VendorMaster>();
            this.VendorMasters2 = new HashSet<VendorMaster>();
        }
    
        public int id { get; set; }
        public string Bank_Name { get; set; }
        public string IFSC_code { get; set; }
        public string Bank_Branch { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public int state { get; set; }
        public int city { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<System.DateTime> DOM { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorMaster> VendorMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorMaster> VendorMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorMaster> VendorMasters2 { get; set; }
    }
}
