//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingMaster()
        {
            this.DeliveryMasters = new HashSet<DeliveryMaster>();
            this.DeliveryMasters1 = new HashSet<DeliveryMaster>();
            this.DeliveryMasters2 = new HashSet<DeliveryMaster>();
            this.DeliveryMasters3 = new HashSet<DeliveryMaster>();
            this.InwardMasters = new HashSet<InwardMaster>();
            this.OutwardMasters = new HashSet<OutwardMaster>();
            this.PackingMasters = new HashSet<PackingMaster>();
            this.TruckUnloadings = new HashSet<TruckUnloading>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> cn { get; set; }
        public Nullable<System.DateTime> expectedDelivery { get; set; }
        public Nullable<int> from { get; set; }
        public Nullable<int> to { get; set; }
        public Nullable<int> godownNo { get; set; }
        public string paymentType { get; set; }
        public Nullable<decimal> actualWeight { get; set; }
        public Nullable<int> consignee { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> cnNo { get; set; }
        public Nullable<int> deliveryBranch { get; set; }
        public Nullable<int> virtualGoddownNo { get; set; }
        public string consignorDetails { get; set; }
        public Nullable<int> consignor { get; set; }
        public Nullable<int> agentName { get; set; }
        public string agentDetails { get; set; }
        public string bookingType { get; set; }
        public string deliveryType { get; set; }
        public string modeOfTransport { get; set; }
        public string invoiceNo { get; set; }
        public string invoiceValue { get; set; }
        public string consignorInvoice { get; set; }
        public string freightBasis { get; set; }
        public string ftl { get; set; }
        public Nullable<bool> isCcAttached { get; set; }
        public Nullable<bool> isCod { get; set; }
        public Nullable<decimal> chargeWeight { get; set; }
        public Nullable<decimal> freightRate { get; set; }
        public string privateMark { get; set; }
        public string insuredBy { get; set; }
        public Nullable<decimal> freight { get; set; }
        public Nullable<decimal> surcharge { get; set; }
        public Nullable<decimal> hamaliCharge { get; set; }
        public string localCartages { get; set; }
        public Nullable<decimal> doorDeliveryCharge { get; set; }
        public Nullable<decimal> statisticalCharges { get; set; }
        public Nullable<decimal> miscellaneousCharges { get; set; }
        public Nullable<decimal> godownCharges { get; set; }
        public Nullable<decimal> cod { get; set; }
        public Nullable<bool> financeEffect { get; set; }
        public string riskCharge { get; set; }
        public string branch { get; set; }
        public Nullable<int> reserveReason { get; set; }
        public Nullable<System.DateTime> cnFrom { get; set; }
        public Nullable<System.DateTime> cnTo { get; set; }
        public Nullable<int> srtoNo { get; set; }
        public Nullable<int> lotNo { get; set; }
        public string rollNo { get; set; }
        public Nullable<decimal> meter { get; set; }
        public Nullable<decimal> weightInKg { get; set; }
    
        public virtual GodownMaster GodownMaster { get; set; }
        public virtual RegularClientMaster RegularClientMaster { get; set; }
        public virtual BookingMaster BookingMaster1 { get; set; }
        public virtual BookingMaster BookingMaster2 { get; set; }
        public virtual GodownMaster GodownMaster1 { get; set; }
        public virtual RegularClientMaster RegularClientMaster1 { get; set; }
        public virtual RegularClientMaster RegularClientMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryMaster> DeliveryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryMaster> DeliveryMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryMaster> DeliveryMasters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryMaster> DeliveryMasters3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaster> InwardMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutwardMaster> OutwardMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackingMaster> PackingMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckUnloading> TruckUnloadings { get; set; }
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual BranchMaster BranchMaster1 { get; set; }
        public virtual BranchMaster BranchMaster2 { get; set; }
    }
}
