//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchMaster()
        {
            this.BookingMasters = new HashSet<BookingMaster>();
            this.BookingMasters1 = new HashSet<BookingMaster>();
            this.BookingMasters2 = new HashSet<BookingMaster>();
            this.ConsignmentOperations = new HashSet<ConsignmentOperation>();
            this.ConsignmentOperations1 = new HashSet<ConsignmentOperation>();
            this.ConsignmentOperations2 = new HashSet<ConsignmentOperation>();
            this.CrossingMasters = new HashSet<CrossingMaster>();
            this.CrossingMasters1 = new HashSet<CrossingMaster>();
            this.DocumentAllocationMasters = new HashSet<DocumentAllocationMaster>();
            this.DocumentSeriesAllocations = new HashSet<DocumentSeriesAllocation>();
            this.FreightMasters = new HashSet<FreightMaster>();
            this.FreightMasters1 = new HashSet<FreightMaster>();
            this.GodownMasters = new HashSet<GodownMaster>();
            this.GodownOwnerDetailsMasters = new HashSet<GodownOwnerDetailsMaster>();
            this.InwardMasters = new HashSet<InwardMaster>();
            this.InwardMasters1 = new HashSet<InwardMaster>();
            this.InwardMasters2 = new HashSet<InwardMaster>();
            this.LocalVehicleContractMasters = new HashSet<LocalVehicleContractMaster>();
            this.OutwardMasters = new HashSet<OutwardMaster>();
            this.OutwardMasters1 = new HashSet<OutwardMaster>();
            this.OutwardMasters2 = new HashSet<OutwardMaster>();
            this.OutwardMasters3 = new HashSet<OutwardMaster>();
            this.RegularClientMasters = new HashSet<RegularClientMaster>();
            this.ServiceLocationMasters = new HashSet<ServiceLocationMaster>();
            this.ServiceLocationMasters1 = new HashSet<ServiceLocationMaster>();
            this.StandardLorryHireMasters = new HashSet<StandardLorryHireMaster>();
            this.TruckArrivals = new HashSet<TruckArrival>();
            this.TruckArrivals1 = new HashSet<TruckArrival>();
            this.TruckArrivals2 = new HashSet<TruckArrival>();
            this.VirtualGodownMasters = new HashSet<VirtualGodownMaster>();
            this.Bills = new HashSet<Bill>();
        }
    
        public int id { get; set; }
        public string branchCode { get; set; }
        public string branchName { get; set; }
        public Nullable<int> branchType { get; set; }
        public string deliveryAgainstAs { get; set; }
        public int cityId { get; set; }
        public Nullable<int> pincode { get; set; }
        public int stateId { get; set; }
        public string gstNo { get; set; }
        public string phoneNo { get; set; }
        public string mobileNo { get; set; }
        public int regionId { get; set; }
        public Nullable<int> areaId { get; set; }
        public string servicesOffered { get; set; }
        public string cn { get; set; }
        public string mr { get; set; }
        public string challan { get; set; }
        public string freightBill { get; set; }
        public Nullable<int> expectedUnderLoad { get; set; }
        public Nullable<int> expectedUnloadingAfterArrival { get; set; }
        public Nullable<int> maxAdvance { get; set; }
        public Nullable<int> defaultCashLedger { get; set; }
        public Nullable<int> defaultBankLedger { get; set; }
        public string remark { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingMaster> BookingMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingMaster> BookingMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingMaster> BookingMasters2 { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentOperation> ConsignmentOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentOperation> ConsignmentOperations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentOperation> ConsignmentOperations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrossingMaster> CrossingMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrossingMaster> CrossingMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentAllocationMaster> DocumentAllocationMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentSeriesAllocation> DocumentSeriesAllocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreightMaster> FreightMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FreightMaster> FreightMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GodownMaster> GodownMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GodownOwnerDetailsMaster> GodownOwnerDetailsMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaster> InwardMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaster> InwardMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaster> InwardMasters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalVehicleContractMaster> LocalVehicleContractMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutwardMaster> OutwardMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutwardMaster> OutwardMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutwardMaster> OutwardMasters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutwardMaster> OutwardMasters3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularClientMaster> RegularClientMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceLocationMaster> ServiceLocationMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceLocationMaster> ServiceLocationMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StandardLorryHireMaster> StandardLorryHireMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckArrival> TruckArrivals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckArrival> TruckArrivals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckArrival> TruckArrivals2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VirtualGodownMaster> VirtualGodownMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
    }
}
