//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractMaster
    {
        public int id { get; set; }
        public string no { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public int branch { get; set; }
        public int clientname { get; set; }
        public string pono { get; set; }
        public string podate { get; set; }
        public System.DateTime validfromdate { get; set; }
        public System.DateTime validtodate { get; set; }
        public string rateapplicableon { get; set; }
        public double weight { get; set; }
        public double freight { get; set; }
        public int branchfrom { get; set; }
        public int branchto { get; set; }
        public string freightperKG { get; set; }
        public double statisticalcharges { get; set; }
        public double FOV { get; set; }
        public double hamaliperKG { get; set; }
        public double hamaniperArt { get; set; }
        public double localcharges { get; set; }
        public double doordeliverychargesKG { get; set; }
        public double doordeliverychargesart { get; set; }
        public double gicharges { get; set; }
        public string demurragedays { get; set; }
        public double demurragerate { get; set; }
        public string fileupload { get; set; }
        public bool isActive { get; set; }
    }
}
