//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDLocalChallan
    {
        public int id { get; set; }
        public string DDlocalchallanNo { get; set; }
        public Nullable<System.DateTime> DDlocalchallanDate { get; set; }
        public string prideliveryNo { get; set; }
        public Nullable<double> Hirecharges { get; set; }
        public Nullable<int> vehicleNo { get; set; }
        public string remark { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual VehicleMaster VehicleMaster { get; set; }
    }
}
