//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAllocationMaster
    {
        public int id { get; set; }
        public System.DateTime generationdate { get; set; }
        public string documenttype { get; set; }
        public double startseriesNo { get; set; }
        public double endseriesNo { get; set; }
        public double count { get; set; }
        public System.DateTime dateofprinting { get; set; }
        public string documenttype1 { get; set; }
        public double startseriesNo1 { get; set; }
        public double endseriesNo1 { get; set; }
        public double count1 { get; set; }
        public System.DateTime dateofallocation { get; set; }
        public int branch { get; set; }
        public string documenettype2 { get; set; }
        public double startseriesNo2 { get; set; }
        public double endseriesNo2 { get; set; }
        public double count2 { get; set; }
        public bool isActive { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
    }
}
