//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DriverMaster()
        {
            this.VehicleMasters = new HashSet<VehicleMaster>();
            this.OutwardMasters = new HashSet<OutwardMaster>();
            this.OutwardMasters1 = new HashSet<OutwardMaster>();
            this.OutwardMasters2 = new HashSet<OutwardMaster>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string drivercategory { get; set; }
        public Nullable<bool> isreliable { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Religion { get; set; }
        public string qualification { get; set; }
        public string maritalstatus { get; set; }
        public string drivinglicencecategory { get; set; }
        public string drivinglicenceNo { get; set; }
        public string drivLiceIssueAuthoLoca { get; set; }
        public Nullable<System.DateTime> drivLiceExDate { get; set; }
        public string bloodgroup { get; set; }
        public string Address { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> city { get; set; }
        public string STDcode { get; set; }
        public string phoneno { get; set; }
        public string mobileno { get; set; }
        public string referencename { get; set; }
        public string referenceaddress { get; set; }
        public Nullable<int> referencecity { get; set; }
        public string referencepincode { get; set; }
        public string referencephoneno { get; set; }
        public string referencemobileno { get; set; }
        public string policyno { get; set; }
        public string insurancecompany { get; set; }
        public string insurancevalue { get; set; }
        public string nomination { get; set; }
        public Nullable<System.DateTime> insuranceexpirydate { get; set; }
        public string fileupload { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
        public virtual CityMaster CityMaster1 { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleMaster> VehicleMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutwardMaster> OutwardMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutwardMaster> OutwardMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutwardMaster> OutwardMasters2 { get; set; }
    }
}
