//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightMaster
    {
        public int id { get; set; }
        public string bookingType { get; set; }
        public string transpotType { get; set; }
        public int frombranch { get; set; }
        public int tobranch { get; set; }
        public double rateperKG { get; set; }
        public double distance { get; set; }
        public double transitdays { get; set; }
        public bool isActive { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual BranchMaster BranchMaster1 { get; set; }
    }
}
