//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalVehicleContractMaster
    {
        public int id { get; set; }
        public int branch { get; set; }
        public int vehicleNo { get; set; }
        public int vendorDetail { get; set; }
        public System.DateTime fromdate { get; set; }
        public System.DateTime todate { get; set; }
        public string freightsettlement { get; set; }
        public string hirebasis { get; set; }
        public string hirerate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual VendorMaster VendorMaster { get; set; }
        public virtual VehicleMaster VehicleMaster { get; set; }
        public virtual BranchMaster BranchMaster { get; set; }
    }
}
