//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TRSEntities4 : DbContext
    {
        public TRSEntities4()
            : base("name=TRSEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaMaster> AreaMasters { get; set; }
        public virtual DbSet<BankMaster> BankMasters { get; set; }
        public virtual DbSet<BranchRate> BranchRates { get; set; }
        public virtual DbSet<CityMaster> CityMasters { get; set; }
        public virtual DbSet<GodownMaster> GodownMasters { get; set; }
        public virtual DbSet<GodownOwnerDetailsMaster> GodownOwnerDetailsMasters { get; set; }
        public virtual DbSet<PackingMaster> PackingMasters { get; set; }
        public virtual DbSet<RegionMaster> RegionMasters { get; set; }
        public virtual DbSet<RegularClient_Contact_info> RegularClient_Contact_info { get; set; }
        public virtual DbSet<RegularClientMaster> RegularClientMasters { get; set; }
        public virtual DbSet<RTOMaster> RTOMasters { get; set; }
        public virtual DbSet<StateMaster> StateMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<VirtualGodownMaster> VirtualGodownMasters { get; set; }
        public virtual DbSet<ServiceLocationMaster> ServiceLocationMasters { get; set; }
        public virtual DbSet<Walk_inClientMaster> Walk_inClientMaster { get; set; }
        public virtual DbSet<CommodityTypeMaster> CommodityTypeMasters { get; set; }
        public virtual DbSet<CommodityMaster> CommodityMasters { get; set; }
        public virtual DbSet<DepartmentMaster> DepartmentMasters { get; set; }
        public virtual DbSet<PackingTypeMaster> PackingTypeMasters { get; set; }
        public virtual DbSet<LateReportReasonMaster> LateReportReasonMasters { get; set; }
        public virtual DbSet<VendorTypeMaster> VendorTypeMasters { get; set; }
        public virtual DbSet<VendorMaster> VendorMasters { get; set; }
        public virtual DbSet<VehicleTypeMaster> VehicleTypeMasters { get; set; }
        public virtual DbSet<VehicleModelMaster> VehicleModelMasters { get; set; }
        public virtual DbSet<FreightMaster> FreightMasters { get; set; }
        public virtual DbSet<ContractMaster> ContractMasters { get; set; }
        public virtual DbSet<CrossingMaster> CrossingMasters { get; set; }
        public virtual DbSet<LocalVehicleContractMaster> LocalVehicleContractMasters { get; set; }
        public virtual DbSet<StandardLorryHireMaster> StandardLorryHireMasters { get; set; }
        public virtual DbSet<VehicleMaster> VehicleMasters { get; set; }
        public virtual DbSet<DocumentAllocationMaster> DocumentAllocationMasters { get; set; }
        public virtual DbSet<InwardMaster> InwardMasters { get; set; }
        public virtual DbSet<DeliveryMaster> DeliveryMasters { get; set; }
        public virtual DbSet<ReceiptMaster> ReceiptMasters { get; set; }
        public virtual DbSet<AccountMaster> AccountMasters { get; set; }
        public virtual DbSet<DriverMaster> DriverMasters { get; set; }
        public virtual DbSet<SeriesGeneration> SeriesGenerations { get; set; }
        public virtual DbSet<PrintingStationary> PrintingStationaries { get; set; }
        public virtual DbSet<DocumentSeriesAllocation> DocumentSeriesAllocations { get; set; }
        public virtual DbSet<ConsignmentOperation> ConsignmentOperations { get; set; }
        public virtual DbSet<UploadPackingSlip> UploadPackingSlips { get; set; }
        public virtual DbSet<TruckArrival> TruckArrivals { get; set; }
        public virtual DbSet<TruckUnloading> TruckUnloadings { get; set; }
        public virtual DbSet<GodownDelivery> GodownDeliveries { get; set; }
        public virtual DbSet<PreDelivery> PreDeliveries { get; set; }
        public virtual DbSet<DDLocalChallan> DDLocalChallans { get; set; }
        public virtual DbSet<DoorDeliveryConfirm> DoorDeliveryConfirms { get; set; }
        public virtual DbSet<OutwardMaster> OutwardMasters { get; set; }
        public virtual DbSet<BookingMaster> BookingMasters { get; set; }
        public virtual DbSet<BranchMaster> BranchMasters { get; set; }
        public virtual DbSet<ReserveBooking> ReserveBookings { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<LedgerGroupFinance> LedgerGroupFinances { get; set; }
        public virtual DbSet<Ledger> Ledgers { get; set; }
        public virtual DbSet<CostCentre> CostCentres { get; set; }
        public virtual DbSet<Requirement> Requirements { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
    }
}
