//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingMaster
    {
        public int id { get; set; }
        public Nullable<int> article { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<decimal> actualWeight { get; set; }
        public string packingType { get; set; }
        public Nullable<int> bookingId { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual BookingMaster BookingMaster { get; set; }
    }
}
