//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptMaster
    {
        public int id { get; set; }
        public string BMRno { get; set; }
        public Nullable<System.DateTime> BMRdate { get; set; }
        public string Cash { get; set; }
        public string Chequeno { get; set; }
        public Nullable<System.DateTime> Chequedate { get; set; }
        public string Receivedamount { get; set; }
        public string Billno { get; set; }
        public string Billamount { get; set; }
        public string TDS { get; set; }
        public string FreightDeduction { get; set; }
        public string Etc { get; set; }
        public string remark { get; set; }
        public string financeeffect { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
