//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegionMaster()
        {
            this.AreaMasters = new HashSet<AreaMaster>();
        }
    
        public int id { get; set; }
        public string regionCode { get; set; }
        public string regionName { get; set; }
        public string address { get; set; }
        public int cityId { get; set; }
        public Nullable<int> pincode { get; set; }
        public int stateId { get; set; }
        public string phoneNo { get; set; }
        public string mobileNo { get; set; }
        public string emailId { get; set; }
        public string cashBalanceLimit { get; set; }
        public string bankBalanceLimit { get; set; }
        public Nullable<int> defaultCashLedger { get; set; }
        public Nullable<int> defaultBankLegder { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AreaMaster> AreaMasters { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
    }
}
