//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegularClientMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegularClientMaster()
        {
            this.RegularClient_Contact_info = new HashSet<RegularClient_Contact_info>();
            this.DeliveryMasters = new HashSet<DeliveryMaster>();
            this.DeliveryMasters1 = new HashSet<DeliveryMaster>();
            this.DeliveryMasters2 = new HashSet<DeliveryMaster>();
            this.DeliveryMasters3 = new HashSet<DeliveryMaster>();
            this.ConsignmentOperations = new HashSet<ConsignmentOperation>();
            this.ConsignmentOperations1 = new HashSet<ConsignmentOperation>();
            this.ConsignmentOperations2 = new HashSet<ConsignmentOperation>();
            this.ConsignmentOperations3 = new HashSet<ConsignmentOperation>();
            this.GodownDeliveries = new HashSet<GodownDelivery>();
            this.GodownDeliveries1 = new HashSet<GodownDelivery>();
            this.PreDeliveries = new HashSet<PreDelivery>();
            this.PreDeliveries1 = new HashSet<PreDelivery>();
            this.BookingMasters = new HashSet<BookingMaster>();
            this.BookingMasters1 = new HashSet<BookingMaster>();
            this.BookingMasters2 = new HashSet<BookingMaster>();
            this.ReserveBookings = new HashSet<ReserveBooking>();
        }
    
        public int id { get; set; }
        public Nullable<int> branchId { get; set; }
        public string clientCode { get; set; }
        public string clientName { get; set; }
        public Nullable<int> clientGroupId { get; set; }
        public string pan { get; set; }
        public string gstIN { get; set; }
        public string address { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<int> pinCode { get; set; }
        public Nullable<int> StateId { get; set; }
        public string phoneNo { get; set; }
        public string mobileNo { get; set; }
        public Nullable<bool> emailAlert { get; set; }
        public Nullable<bool> smsAlert { get; set; }
        public string deliveryAgainstAsCnr { get; set; }
        public string deliveryAgainstAsCne { get; set; }
        public string ledgerName { get; set; }
        public string CreditLimit { get; set; }
        public Nullable<int> days { get; set; }
        public string amount { get; set; }
        public Nullable<int> interest { get; set; }
        public Nullable<int> creditGraceDays { get; set; }
        public Nullable<int> bankId { get; set; }
        public string ifsc { get; set; }
        public string accountNo { get; set; }
        public string chequeInTheNameOf { get; set; }
        public string companyNo { get; set; }
        public string policyNo { get; set; }
        public Nullable<System.DateTime> validFromDate { get; set; }
        public Nullable<System.DateTime> validToDate { get; set; }
        public string insuranceAmount { get; set; }
        public Nullable<bool> isMarineInsured { get; set; }
        public Nullable<bool> isGodownInsured { get; set; }
        public string paymentMode { get; set; }
        public string bookingType { get; set; }
        public string deliveryType { get; set; }
        public string multipleBillingBranches { get; set; }
        public string remark { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularClient_Contact_info> RegularClient_Contact_info { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryMaster> DeliveryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryMaster> DeliveryMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryMaster> DeliveryMasters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryMaster> DeliveryMasters3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentOperation> ConsignmentOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentOperation> ConsignmentOperations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentOperation> ConsignmentOperations2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignmentOperation> ConsignmentOperations3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GodownDelivery> GodownDeliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GodownDelivery> GodownDeliveries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreDelivery> PreDeliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreDelivery> PreDeliveries1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingMaster> BookingMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingMaster> BookingMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingMaster> BookingMasters2 { get; set; }
        public virtual BranchMaster BranchMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReserveBooking> ReserveBookings { get; set; }
    }
}
