//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public int id { get; set; }
        public string requirementNo { get; set; }
        public Nullable<System.DateTime> requirementDate { get; set; }
        public string requirementType { get; set; }
        public Nullable<int> DRLedgerNameTo { get; set; }
        public string DRAmount { get; set; }
        public Nullable<int> DRLedgerNameFrom { get; set; }
        public string DRAmount1 { get; set; }
        public string remark { get; set; }
        public string referenceNo { get; set; }
        public string challanNo { get; set; }
        public string RENT { get; set; }
        public string SALARY { get; set; }
        public string ADMIN { get; set; }
        public string fileupload { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string rejectremark { get; set; }
    
        public virtual Ledger Ledger { get; set; }
        public virtual Ledger Ledger1 { get; set; }
    }
}
