//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReserveBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReserveBooking()
        {
            this.DoorDeliveryConfirms = new HashSet<DoorDeliveryConfirm>();
            this.GodownDeliveries = new HashSet<GodownDelivery>();
            this.PreDeliveries = new HashSet<PreDelivery>();
        }
    
        public int id { get; set; }
        public Nullable<int> branch { get; set; }
        public Nullable<int> Consignor { get; set; }
        public string CNfrom { get; set; }
        public string CNto { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoorDeliveryConfirm> DoorDeliveryConfirms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GodownDelivery> GodownDeliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreDelivery> PreDeliveries { get; set; }
        public virtual RegularClientMaster RegularClientMaster { get; set; }
    }
}
