//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTOMaster
    {
        public int id { get; set; }
        public string rtoCode { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<int> city { get; set; }
        public string pinCode { get; set; }
        public Nullable<int> state { get; set; }
        public string stdCode { get; set; }
        public Nullable<int> phoneNo { get; set; }
        public string emailId { get; set; }
        public string website { get; set; }
        public string remark { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> mobileNo { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
    }
}
