//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeriesGeneration
    {
        public int id { get; set; }
        public Nullable<System.DateTime> generationdate { get; set; }
        public string documenttype { get; set; }
        public Nullable<double> startseriesNo { get; set; }
        public Nullable<double> endseriesNo { get; set; }
        public Nullable<double> count { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
