//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceLocationMaster
    {
        public int Id { get; set; }
        public string servicelocationcode { get; set; }
        public string servicelocationname { get; set; }
        public string defaultdeliverytype { get; set; }
        public int controllingbranch { get; set; }
        public int deliveryat { get; set; }
        public string distancefrombranch { get; set; }
        public string istodaybooking { get; set; }
        public string pickupcharges { get; set; }
        public string DDCharges { get; set; }
        public bool isActive { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual BranchMaster BranchMaster1 { get; set; }
    }
}
