//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardLorryHireMaster
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int vehicleType { get; set; }
        public double vehiclecpacityMT { get; set; }
        public int from { get; set; }
        public int to { get; set; }
        public string lorryhire { get; set; }
        public bool isActive { get; set; }
    
        public virtual VehicleTypeMaster VehicleTypeMaster { get; set; }
        public virtual VehicleTypeMaster VehicleTypeMaster1 { get; set; }
        public virtual BranchMaster BranchMaster { get; set; }
    }
}
