//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TruckArrival
    {
        public int id { get; set; }
        public string truckArrivalNo { get; set; }
        public Nullable<System.DateTime> truckArrivalDate { get; set; }
        public Nullable<int> vehicleNo { get; set; }
        public string challanNo { get; set; }
        public Nullable<System.DateTime> challanDate { get; set; }
        public Nullable<int> challanFrom { get; set; }
        public Nullable<int> challanTo { get; set; }
        public Nullable<System.DateTime> scheduledArriDate { get; set; }
        public Nullable<int> expectedUnloadingTime { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual VehicleMaster VehicleMaster { get; set; }
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual BranchMaster BranchMaster1 { get; set; }
        public virtual BranchMaster BranchMaster2 { get; set; }
    }
}
