//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadPackingSlip
    {
        public int id { get; set; }
        public Nullable<int> cnNo { get; set; }
        public string rollNo { get; set; }
        public Nullable<int> srtoNo { get; set; }
        public Nullable<int> lotNo { get; set; }
        public Nullable<double> meter { get; set; }
        public Nullable<double> weightInKg { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
