//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleMaster()
        {
            this.LocalVehicleContractMasters = new HashSet<LocalVehicleContractMaster>();
            this.InwardMasters = new HashSet<InwardMaster>();
            this.InwardMasters1 = new HashSet<InwardMaster>();
            this.TruckArrivals = new HashSet<TruckArrival>();
            this.TruckUnloadings = new HashSet<TruckUnloading>();
            this.DDLocalChallans = new HashSet<DDLocalChallan>();
            this.OutwardMasters = new HashSet<OutwardMaster>();
        }
    
        public int id { get; set; }
        public string vehiclecategory { get; set; }
        public string vehicleNo { get; set; }
        public int vehicleType { get; set; }
        public int manufacturer { get; set; }
        public int vehiclemodel { get; set; }
        public string yearofmanufacturing { get; set; }
        public string GPSID { get; set; }
        public int drivername { get; set; }
        public int ownerdetails { get; set; }
        public string chassisNo { get; set; }
        public string engineNo { get; set; }
        public string trollychassisNo { get; set; }
        public string fueltankCapacity { get; set; }
        public double vehicleweightinMT { get; set; }
        public double unladenweightinMT { get; set; }
        public double vehicleCapacity { get; set; }
        public double wheelbaseinMM { get; set; }
        public double lengthinFt { get; set; }
        public double widthinft { get; set; }
        public double heightinft { get; set; }
        public double powerinCC { get; set; }
        public string paintCode { get; set; }
        public string paintColour { get; set; }
        public string ignitionkey { get; set; }
        public double doorkeycode { get; set; }
        public int bankfanainstuName { get; set; }
        public string loanaccountNo { get; set; }
        public string fileUpload { get; set; }
        public string wheelsize { get; set; }
        public string tyresize { get; set; }
        public string psi { get; set; }
        public System.DateTime registrationDate { get; set; }
        public System.DateTime fitnessDate { get; set; }
        public System.DateTime permitfromdate { get; set; }
        public System.DateTime insurancefromdate { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalVehicleContractMaster> LocalVehicleContractMasters { get; set; }
        public virtual VehicleModelMaster VehicleModelMaster { get; set; }
        public virtual VehicleTypeMaster VehicleTypeMaster { get; set; }
        public virtual VendorMaster VendorMaster { get; set; }
        public virtual VendorMaster VendorMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaster> InwardMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InwardMaster> InwardMasters1 { get; set; }
        public virtual DriverMaster DriverMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckArrival> TruckArrivals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TruckUnloading> TruckUnloadings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DDLocalChallan> DDLocalChallans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutwardMaster> OutwardMasters { get; set; }
    }
}
