//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleModelMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehicleModelMaster()
        {
            this.VehicleMasters = new HashSet<VehicleMaster>();
        }
    
        public int id { get; set; }
        public string modelname { get; set; }
        public int manufacturername { get; set; }
        public double vehicleweightinMT { get; set; }
        public double unladenweightinMT { get; set; }
        public double vehiclecapacity { get; set; }
        public double length { get; set; }
        public double width { get; set; }
        public double height { get; set; }
        public bool isActive { get; set; }
    
        public virtual VendorMaster VendorMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleMaster> VehicleMasters { get; set; }
    }
}
