//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorMaster()
        {
            this.VehicleModelMasters = new HashSet<VehicleModelMaster>();
            this.LocalVehicleContractMasters = new HashSet<LocalVehicleContractMaster>();
            this.VehicleMasters = new HashSet<VehicleMaster>();
            this.VehicleMasters1 = new HashSet<VehicleMaster>();
            this.OutwardMasters = new HashSet<OutwardMaster>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int vendorType { get; set; }
        public string address { get; set; }
        public int city { get; set; }
        public string pincode { get; set; }
        public int state { get; set; }
        public string STDcode { get; set; }
        public string phoneno { get; set; }
        public string mobileno { get; set; }
        public string emailid { get; set; }
        public bool emailalert { get; set; }
        public bool mobilealert { get; set; }
        public string PAN { get; set; }
        public string GSTIN { get; set; }
        public string referencename { get; set; }
        public string referphoneno { get; set; }
        public string refermobileno { get; set; }
        public string creditdays { get; set; }
        public string creditamount { get; set; }
        public int bankname { get; set; }
        public int bankbranch { get; set; }
        public int IFSC { get; set; }
        public string accountno { get; set; }
        public string chequename { get; set; }
        public string fileupload { get; set; }
        public bool isActive { get; set; }
    
        public virtual BankMaster BankMaster { get; set; }
        public virtual BankMaster BankMaster1 { get; set; }
        public virtual BankMaster BankMaster2 { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        public virtual VendorTypeMaster VendorTypeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleModelMaster> VehicleModelMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalVehicleContractMaster> LocalVehicleContractMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleMaster> VehicleMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleMaster> VehicleMasters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutwardMaster> OutwardMasters { get; set; }
    }
}
